<div class="flights-banner"></div>
<div class='container-fluid home-0'>
    <section class="product-detail col-xs-12" style="transform: none;">
        <div class="container about" style="transform: none;">
            <div class="row">
                <div class="col-sm-3 sidebar">
                    <h3 class="sansa text-green">Useful Links</h3>
                    <ul>
                        <li><a href="https://www.facebook.com/FunTravel-Roppongi-169642149753285/">Follow on Facebook</a></li>
                        <li><a href="https://twitter.com/FunTravelTokyo">Follow on Twitter</a></li>
                        <li><a href="<?= base_url('transfers') ?>">Transfers</a></li>
                        <li><a href="<?= base_url('airlines') ?>">Airlines</a></li>
                        <li><a href="<?= base_url('mileage') ?>">Mileage</a></li>
                        <li><a href="<?= base_url('embassies') ?>">Embassies</a></li>
                    </ul>
                </div>
                <div class="col-sm-9 airlines main">
                    <h2 class="sans text-green"><u>EMBASSIES</u></h2>
                    <h3 class="sans">PHONE NUMBERS</h3>
                    <table cellspacing="0" cellpadding="0" width="100%">
                        <tbody>
                            <tr>
                                <td width="180"><strong>Algeria</strong></td>
                                <td>03-3711-2661</td>
                                <td width="180"><strong>Libya</strong></td>
                                <td>03-3477-0701</td>
                            </tr>
                            <tr>
                                <td><strong>Argentina</strong></td>
                                <td>03-5420-7101</td>
                                <td><strong>Luxembourg</strong></td>
                                <td>03-3265-9621</td>
                            </tr>
                            <tr>
                                <td><strong>Australia</strong></td>
                                <td>03-5232-4111</td>
                                <td><strong>Madagascar</strong></td>
                                <td>03-3446-7252</td>
                            </tr>
                            <tr>
                                <td><strong>Austria</strong></td>
                                <td>03-3451-8281</td>
                                <td><strong>Malaysia</strong></td>
                                <td>03-3476-3840</td>
                            </tr>
                            <tr>
                                <td><strong>Bangladesh</strong></td>
                                <td>03-5704-0216</td>
                                <td><strong>Mexico</strong></td>
                                <td>03-3581-1131</td>
                            </tr>
                            <tr>
                                <td><strong>Belgium</strong></td>
                                <td>03-3262-0191</td>
                                <td><strong>Mongolia</strong></td>
                                <td>03-3469-2088</td>
                            </tr>
                            <tr>
                                <td><strong>Bolivia</strong></td>
                                <td>03-3499-5441</td>
                                <td><strong>Morocco</strong></td>
                                <td>03-3478-3271</td>
                            </tr>
                            <tr>
                                <td><strong>Brazil</strong></td>
                                <td>03-3404-5211</td>
                                <td><strong>Myanmar</strong></td>
                                <td>03-3441-9291</td>
                            </tr>
                            <tr>
                                <td><strong>Bulgaria</strong></td>
                                <td>03-3465-1021</td>
                                <td><strong>Nepal</strong></td>
                                <td>03-3705-5558</td>
                            </tr>
                            <tr>
                                <td><strong>Canada</strong></td>
                                <td>03-5412-6200</td>
                                <td><strong>The Netherlands</strong></td>
                                <td>03-5401-0411</td>
                            </tr>
                            <tr>
                                <td><strong>Chile</strong></td>
                                <td>03-3452-7561</td>
                                <td><strong>New Zealand</strong></td>
                                <td>03-3467-2271</td>
                            </tr>
                            <tr>
                                <td><strong>China</strong></td>
                                <td>03-3403-3380</td>
                                <td><strong>Nicaragua</strong></td>
                                <td>03-3499-0400</td>
                            </tr>
                            <tr>
                                <td><strong>Colombia</strong></td>
                                <td>03-3440-6451</td>
                                <td><strong>Nigeria</strong></td>
                                <td>03-5721-5391</td>
                            </tr>
                            <tr>
                                <td><strong>Congo</strong></td>
                                <td>03-5820-1581</td>
                                <td><strong>Norway</strong></td>
                                <td>03-3440-2611</td>
                            </tr>
                            <tr>
                                <td><strong>Costa Rica</strong></td>
                                <td>03-3486-1812</td>
                                <td><strong>Oman</strong></td>
                                <td>03-3402-0877</td>
                            </tr>
                            <tr>
                                <td><strong>Cote D'Ivoire</strong></td>
                                <td>03-5454-1401</td>
                                <td><strong>Pakistan</strong></td>
                                <td>03-3454-4861</td>
                            </tr>
                            <tr>
                                <td><strong>Cuba</strong></td>
                                <td>03-5570-3182</td>
                                <td><strong>Panama</strong></td>
                                <td>03-3499-3741</td>
                            </tr>
                            <tr>
                                <td><strong>Czech &amp; Slovakia</strong></td>
                                <td>03-3400-8122</td>
                                <td><strong>Papua New Guinea</strong></td>
                                <td>03-3454-7801</td>
                            </tr>
                            <tr>
                                <td><strong>Denmark</strong></td>
                                <td>03-3496-3001</td>
                                <td><strong>Paraguay</strong></td>
                                <td>03-3443-9703</td>
                            </tr>
                            <tr>
                                <td><strong>Dominican Republic</strong></td>
                                <td>03-3499-6020</td>
                                <td><strong>Peru</strong></td>
                                <td>03-3406-4243</td>
                            </tr>
                            <tr>
                                <td><strong>Ecuador</strong></td>
                                <td>03-3499-2800</td>
                                <td><strong>Philippines</strong></td>
                                <td>03-5562-1600</td>
                            </tr>
                            <tr>
                                <td><strong>Egypt</strong></td>
                                <td>03-3770-8022</td>
                                <td><strong>Poland</strong></td>
                                <td>03-3280-2881</td>
                            </tr>
                            <tr>
                                <td><strong>El Salvador</strong></td>
                                <td>03-3499-4461</td>
                                <td><strong>Portugal</strong></td>
                                <td>03-5212-7322</td>
                            </tr>
                            <tr>
                                <td><strong>Ethiopia</strong></td>
                                <td>03-5420-6860</td>
                                <td><strong>Qatar</strong></td>
                                <td>03-5475-0611</td>
                            </tr>
                            <tr>
                                <td><strong>Fiji</strong></td>
                                <td>03-3587-2038</td>
                                <td><strong>Romania</strong></td>
                                <td>03-3479-0311</td>
                            </tr>
                            <tr>
                                <td><strong>Finland</strong></td>
                                <td>03-5447-6000</td>
                                <td><strong>Russian Federation</strong></td>
                                <td>03-3583-4224</td>
                            </tr>
                            <tr>
                                <td><strong>France</strong></td>
                                <td>03-5420-8800</td>
                                <td><strong>Rwanda</strong></td>
                                <td>03-3486-7800</td>
                            </tr>
                            <tr>
                                <td><strong>Gabon</strong></td>
                                <td>03-5430-9171</td>
                                <td><strong>Saudi Arabia</strong></td>
                                <td>03-3589-5241</td>
                            </tr>
                            <tr>
                                <td><strong>Germany</strong></td>
                                <td>03-3473-0151</td>
                                <td><strong>Senegal</strong></td>
                                <td>03-3464-8451</td>
                            </tr>
                            <tr>
                                <td><strong>Ghana</strong></td>
                                <td>03-5410-8631</td>
                                <td><strong>Singapore</strong></td>
                                <td>03-3586-9111</td>
                            </tr>
                            <tr>
                                <td><strong>Greece</strong></td>
                                <td>03-3403-0871</td>
                                <td><strong>Spain</strong></td>
                                <td>03-3583-8531</td>
                            </tr>
                            <tr>
                                <td><strong>Guatemala</strong></td>
                                <td>03-3400-1830</td>
                                <td><strong>Sri Lanka</strong></td>
                                <td>03-3440-6911</td>
                            </tr>
                            <tr>
                                <td><strong>Guinea</strong></td>
                                <td>03-3770-4640</td>
                                <td><strong>Sudan</strong></td>
                                <td>03-3506-7801</td>
                            </tr>
                            <tr>
                                <td><strong>Haiti</strong></td>
                                <td>03-3486-7096</td>
                                <td><strong>Sweden</strong></td>
                                <td>03-3506-5050</td>
                            </tr>
                            <tr>
                                <td><strong>Honduras</strong></td>
                                <td>03-3409-1150</td>
                                <td><strong>Switzerland</strong></td>
                                <td>03-3473-6090</td>
                            </tr>
                            <tr>
                                <td><strong>Hungary</strong></td>
                                <td>03-3798-8801</td>
                                <td><strong>Syria</strong></td>
                                <td>03-3586-8977</td>
                            </tr>
                            <tr>
                                <td><strong>India</strong></td>
                                <td>03-3262-2391</td>
                                <td><strong>Tanzania</strong></td>
                                <td>03-3425-4531</td>
                            </tr>
                            <tr>
                                <td><strong>Indonesia</strong></td>
                                <td>03-3441-4201</td>
                                <td><strong>Thailand</strong></td>
                                <td>03-3441-1386</td>
                            </tr>
                            <tr>
                                <td><strong>Iran</strong></td>
                                <td>03-3446-8011</td>
                                <td><strong>Tunisia</strong></td>
                                <td>03-3511-6622</td>
                            </tr>
                            <tr>
                                <td><strong>Iraq</strong></td>
                                <td>03-5449-3231</td>
                                <td><strong>Turkey</strong></td>
                                <td>03-3470-5131</td>
                            </tr>
                            <tr>
                                <td><strong>Ireland</strong></td>
                                <td>03-3263-0695</td>
                                <td><strong>U.K.</strong></td>
                                <td>03-5211-1100</td>
                            </tr>
                            <tr>
                                <td><strong>Israel</strong></td>
                                <td>03-3264-0911</td>
                                <td><strong>United Arab Emirates</strong></td>
                                <td>03-5489-0804</td>
                            </tr>
                            <tr>
                                <td><strong>Italy</strong></td>
                                <td>03-3453-5291</td>
                                <td><strong>Uruguay</strong></td>
                                <td>03-3486-1888</td>
                            </tr>
                            <tr>
                                <td><strong>Jordan</strong></td>
                                <td>03-3580-5856</td>
                                <td><strong>U.S.A</strong></td>
                                <td>03-3224-5000</td>
                            </tr>
                            <tr>
                                <td><strong>Kenya</strong></td>
                                <td>03-3723-4006</td>
                                <td><strong>Vatican</strong></td>
                                <td>03-3263-6851</td>
                            </tr>
                            <tr>
                                <td><strong>Kiribati</strong></td>
                                <td>03-5411-5967</td>
                                <td><strong>Venezuela</strong></td>
                                <td>03-3409-1501</td>
                            </tr>
                            <tr>
                                <td><strong>Korea</strong></td>
                                <td>03-3452-7611</td>
                                <td><strong>Vietnam</strong></td>
                                <td>03-3466-4209</td>
                            </tr>
                            <tr>
                                <td><strong>Kuwait</strong></td>
                                <td>03-3455-0361</td>
                                <td><strong>Yemen</strong></td>
                                <td>03-3499-7151</td>
                            </tr>
                            <tr>
                                <td><strong>Laos</strong></td>
                                <td>03-5411-2291</td>
                                <td><strong>Yugoslavia</strong></td>
                                <td>03-3447-3571</td>
                            </tr>
                            <tr>
                                <td><strong>Lebanon</strong></td>
                                <td>03-3580-1227</td>
                                <td><strong>Zambia</strong></td>
                                <td>03-3491-0121</td>
                            </tr>
                            <tr>
                                <td><strong>Liberia</strong></td>
                                <td>03-3949-8046</td>
                                <td><strong>Zimbabwe</strong></td>
                                <td>03-3280-0331</td>
                            </tr>
                            <tr>
                                <td><strong>Cambodia</strong></td>
                                <td>03-5412-8521</td>
                                <td><strong>Cameroon</strong></td>
                                <td>03-5430-4985</td>
                            </tr>
                            <tr>
                                <td><strong>Croatia</strong></td>
                                <td>03-5469-3014</td>
                                <td>　</td>
                                <td>　</td>
                            </tr>
                        </tbody></table>
                </div>
            </div>
        </div>
    </section>
</div>